name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-13
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-linux
          path: build/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: build/

  package-linux:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Download linux build artefacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-linux
          path: download/
      - name: Package Linux
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: GameSaveSyncClient-Linux-x86_64
          path: download/bin/Release/GameSaveSyncClient

  package-windows:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Download windows build artefacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-windows
          path: download/
      - name: Build Windows ZIP
        run: |
          mkdir -p deploy
          copy download\bin\Release\GameSaveSyncClient.exe deploy\
          $windeployqt = (Get-ChildItem -Path "${{ steps.install-qt.outputs.Qt6_DIR }}\.." `
              -Recurse -Filter windeployqt.exe | Select-Object -First 1).FullName
          & $windeployqt `
              --release `
              --no-translations `
              --no-opengl-sw `
              --include-soft-plugins `
              --compiler-runtime `
              deploy\GameSaveSyncClient.exe
          7z a GameSaveSyncClient-Windows.zip deploy\*
      - name: Package Windows
        uses: actions/upload-artifact@v4
        with:
          name: GameSaveSyncClient-Windows-ZIP
          path: GameSaveSyncClient-Windows.zip

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [package-windows, package-linux]
    runs-on: ubuntu-24.04
    steps:
      - name: Download windows build package
        uses: actions/download-artifact@v4
        with:
          name: GameSaveSyncClient-Windows-ZIP
          path: windows/
      - name: Download linux build package
        uses: actions/download-artifact@v4
        with:
          name: GameSaveSyncClient-Linux-x86_64
          path: linux/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows/*
            linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
